simulate-en.rst translation
simaple-team/simaple pull request #157
Opened 2023-01-24 08:06 UTC by amphipath

also includes typo fixes for tutorial-en.rst

2023-01-25 08:02 UTC, oleneyl requested changes

2023-01-25 17:02 UTC, amphipath commented on docs/modules/simulate_en.rst
> +Actions correspond to commands given to the character in-game. The Action is to either press a specific skill, or to wait for a specific time without any actions.
"without any input" sounds better. will change it to that

2023-01-25 17:07 UTC, amphipath commented on docs/modules/simulate_en.rst
> +The keys used here must match the variable names in the previously declared ``AttackSkillState``, or else the program will not be able to recognise which Entity the default value provided corresponds
https://www.cambridge.org/elt/blog/2017/09/08/american-british-english-spelling/

학교에 영국의 영어 찰자법 배워서 이렇다. 원하면 미국의 찰자법으로 표준 가능

2023-01-26 05:52 UTC, oleneyl commented on docs/modules/simulate_en.rst
> +The keys used here must match the variable names in the previously declared ``AttackSkillState``, or else the program will not be able to recognise which Entity the default value provided corresponds
then recognise is OK

2023-01-27 09:49 UTC, oleneyl approved these changes

2023-01-27 09:49 UTC, merged