feat: use ArithmeticPatch as name
simaple-team/simaple pull request #224
Opened 2024-09-13 17:38 UTC by oleneyl

2024-09-13 17:52 UTC, icepeng requested changes

2024-09-13 17:52 UTC, icepeng commented on simaple/spec/patch.py
`return eval(value, global_variables) # pylint: disable=W0123`
issue: implementation does not match it's name.

2024-09-15 00:23 UTC, oleneyl commented on simaple/spec/patch.py
9f32be37cf350e0c9140ff4f35f402cd167eecdc
8177cda0a58730b7d6bc436628a1befa556a3c74

2024-09-16 06:31 UTC, icepeng approved these changes
less magic

2024-09-16 06:32 UTC, icepeng commented on simaple/spec/_math.py
> +         | term "<" factor -> lt
question: gt, lt가 필요한 상황이 있나요?

2024-09-16 07:33 UTC, oleneyl commented on simaple/spec/_math.py
> +         | term "<" factor -> lt
skill level이 1이상일때만 적용되어야 하는 경우에는 써야하더라고요

2024-09-16 07:33 UTC, merged